### ISSUE TITLE
Set Up Github Actions

### ISSUE THREAD

**Issue by SPlanzer** [linz/gazetteer#25]
GitHub Actions should be set up to ensure best source code management and coding practices are followed.

## Done

The issues is considered complete once:
Github Actions are 
* running linting
* running format analysis

**Comment by SPlanzer** [comment]
This is to be deferred until development starts. 

looking a simple github action job below there is nothing to run i.e. all linting and formatting will fail and there are no tests to execute. 

This is to be closed and actions will be built as linting, formatting and testing is addressed 

```
name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Format
        run: |
          black src/ --check --diff
          black tests/ --check --diff

      - name: Lint
        run: |
          pylint src/
          pylint tests/

      - name: Test
        run: python -m pytest

      - name: Coverage
        run: |
          pytest --cov
```
